# Generated by Django 6.0.5 on 2026-07-13 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('productos', '0003_alter_productos_options_remove_productos_apellido_and_more'),
        ('proveedores', '0002_alter_proveedores_options_proveedores_estado_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='compras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio', models.CharField(max_length=100)),
                ('fecha', models.DateField(max_length=100)),
                ('subtotal', models.FloatField(max_length=100)),
                ('iva', models.FloatField(max_length=100)),
                ('total', models.FloatField(max_length=100)),
                ('estado', models.CharField(default='Activo', max_length=20)),
                ('productos', models.ManyToManyField(db_table='tbl_inventario_productos', related_name='inventario_productos_rel', to='productos.productos')),
                ('proveedores', models.ManyToManyField(db_table='tbl_inventario_proveedores', related_name='inventario_proveedores_rel', to='proveedores.proveedores')),
            ],
        ),
    ]
