# Generated by Django 6.0.5 on 2026-07-02 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        ('productos', '0002_remove_productos_sexo_alter_productos_apellido'),
    ]

    operations = [
        migrations.CreateModel(
            name='ventas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio', models.CharField()),
                ('fecha', models.DateField()),
                ('subtotal', models.FloatField()),
                ('iva', models.FloatField()),
                ('total', models.FloatField()),
                ('clientes', models.ManyToManyField(to='clientes.clientes')),
                ('productos', models.ManyToManyField(to='productos.productos')),
            ],
        ),
    ]
