# Generated by Django 6.0.5 on 2026-07-13 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ventas',
            name='estado',
            field=models.CharField(default='Activo', max_length=20),
        ),
        migrations.AlterField(
            model_name='ventas',
            name='fecha',
            field=models.DateField(max_length=100),
        ),
        migrations.AlterField(
            model_name='ventas',
            name='folio',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='ventas',
            name='iva',
            field=models.FloatField(max_length=100),
        ),
        migrations.AlterField(
            model_name='ventas',
            name='subtotal',
            field=models.FloatField(max_length=100),
        ),
        migrations.AlterField(
            model_name='ventas',
            name='total',
            field=models.FloatField(max_length=100),
        ),
    ]
