# Generated by Django 6.0.5 on 2026-07-13 01:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='empleados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('sexo', models.CharField(max_length=10)),
                ('tipo', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=200)),
                ('estado', models.CharField(default='Activo', max_length=10)),
                ('jefe_o_supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nomina', to='empleados.empleados')),
            ],
            options={
                'verbose_name_plural': 'Empleados',
            },
        ),
    ]
