# Generated by Django 6.0.5 on 2026-07-01 23:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='grupos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField()),
                ('apellido', models.CharField()),
                ('sexo', models.CharField()),
                ('tipo', models.CharField()),
                ('direccion', models.CharField()),
                ('usuarios', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grupos', to='usuarios.usuarios')),
            ],
        ),
    ]
