# Generated by Django 6.0.5 on 2026-07-05 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_grupos'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuarios',
            options={'verbose_name_plural': 'Usuarios'},
        ),
        migrations.AddField(
            model_name='usuarios',
            name='estado',
            field=models.CharField(default='Activo', max_length=10),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='apellido',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='direccion',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='sexo',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='tipo',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='grupos',
        ),
    ]
