# Generated by Django 6.0.5 on 2026-06-29 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productos',
            name='sexo',
        ),
        migrations.AlterField(
            model_name='productos',
            name='apellido',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
