# Generated by Django 6.0.5 on 2026-07-05 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_remove_productos_sexo_alter_productos_apellido'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productos',
            options={'verbose_name_plural': 'Productos'},
        ),
        migrations.RemoveField(
            model_name='productos',
            name='apellido',
        ),
        migrations.AddField(
            model_name='productos',
            name='estado',
            field=models.CharField(default='Activo', max_length=10),
        ),
        migrations.AlterField(
            model_name='productos',
            name='direccion',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='productos',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='productos',
            name='tipo',
            field=models.CharField(max_length=100),
        ),
    ]
