# Generated by Django 6.0.5 on 2026-07-15 03:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sucursal', '0002_sucursal_ciudad'),
    ]

    operations = [
        migrations.AddField(
            model_name='sucursal',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
