# Generated by Django 6.0.5 on 2026-07-02 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('productos', '0002_remove_productos_sexo_alter_productos_apellido'),
        ('proveedores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='compras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio', models.CharField()),
                ('fecha', models.DateField()),
                ('subtotal', models.FloatField()),
                ('iva', models.FloatField()),
                ('total', models.FloatField()),
                ('productos', models.ManyToManyField(to='productos.productos')),
                ('proveedores', models.ManyToManyField(to='proveedores.proveedores')),
            ],
        ),
    ]
