# Generated by Django 6.0.5 on 2026-07-13 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0001_initial'),
        ('productos', '0003_alter_productos_options_remove_productos_apellido_and_more'),
        ('proveedores', '0002_alter_proveedores_options_proveedores_estado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='compras',
            name='estado',
            field=models.CharField(default='Activo', max_length=20),
        ),
        migrations.AlterField(
            model_name='compras',
            name='fecha',
            field=models.DateField(max_length=100),
        ),
        migrations.AlterField(
            model_name='compras',
            name='folio',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='compras',
            name='iva',
            field=models.FloatField(max_length=100),
        ),
        migrations.AlterField(
            model_name='compras',
            name='productos',
            field=models.ManyToManyField(db_table='tbl_compras_productos', related_name='compras_productos_rel', to='productos.productos'),
        ),
        migrations.AlterField(
            model_name='compras',
            name='proveedores',
            field=models.ManyToManyField(db_table='tbl_compras_proveedores', related_name='compras_proveedores_rel', to='proveedores.proveedores'),
        ),
        migrations.AlterField(
            model_name='compras',
            name='subtotal',
            field=models.FloatField(max_length=100),
        ),
        migrations.AlterField(
            model_name='compras',
            name='total',
            field=models.FloatField(max_length=100),
        ),
    ]
