# Generated by Django 6.0.5 on 2026-07-05 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proveedores',
            options={'verbose_name_plural': 'Proveedores'},
        ),
        migrations.AddField(
            model_name='proveedores',
            name='estado',
            field=models.CharField(default='Activo', max_length=10),
        ),
        migrations.AlterField(
            model_name='proveedores',
            name='apellido',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='proveedores',
            name='direccion',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='proveedores',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='proveedores',
            name='sexo',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='proveedores',
            name='tipo',
            field=models.CharField(max_length=100),
        ),
    ]
